apiVersion: v1alpha1
kind: PruneConfig
# Entries in the selectors define deletion/pruning criteria.
# Entries are OR-ed while properies in an entry are AND-ed.
# Entry can contain:
# - matchExpression: matches the file name.
# - tags: filters by tags on the file.
# - lastAccessDate: 
selectors:
# This matches file ending with suffix .pdf
- matchExpression: "^.*\.pdf$"
  tags: null
  lastAccessDate: null
# This matches files ending with suffix .pdf and have the following tags.
- matchExpression: "*.pdf"
  tags:
    k8s.io/ack-s3: owned
    some-other-tag: value
  withoutTagKeys: ["keyA", "keyB"]
# Remove old files up until a time
  lastAccessDate:
	   to: "YYYY-MM-DD HH:mm:ss" 
  objMetadata:
		 key1: val1
# This matches files last accessed within specified range.
# Either from/to can be omitted to denote after/before.
# timezone is optional. Default to UTC if no timezone provided.
- lastAccessDate:
    timezone: UTC
    from: "YYYY-MM-DD HH:mm:ss"
    to: "YYYY-MM-DD HH:mm:ss"
  matchExpression: null
  tags: null